// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-lT02c3Ry90CYf9x_Qibys9PEhzwy2mU',
    appId: '1:820561191348:web:925ea006b96f2f164952e1',
    messagingSenderId: '820561191348',
    projectId: 'signbuddy-d3d91',
    authDomain: 'signbuddy-d3d91.firebaseapp.com',
    storageBucket: 'signbuddy-d3d91.appspot.com',
    measurementId: 'G-38J3NB3J5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugrVMr0hdDiywW1dNk9O2FMutZQCPQmo',
    appId: '1:820561191348:android:a27545e109d4161f4952e1',
    messagingSenderId: '820561191348',
    projectId: 'signbuddy-d3d91',
    storageBucket: 'signbuddy-d3d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgP3FK_GUCLecd7jLmbdJ7nlI5aO6G1Rk',
    appId: '1:820561191348:ios:ecd24d2df9b1047d4952e1',
    messagingSenderId: '820561191348',
    projectId: 'signbuddy-d3d91',
    storageBucket: 'signbuddy-d3d91.appspot.com',
    iosClientId: '820561191348-g2s3qrqoh7np7r4dvjjceplc2v2jcc94.apps.googleusercontent.com',
    iosBundleId: 'com.example.signBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgP3FK_GUCLecd7jLmbdJ7nlI5aO6G1Rk',
    appId: '1:820561191348:ios:011d911778f673504952e1',
    messagingSenderId: '820561191348',
    projectId: 'signbuddy-d3d91',
    storageBucket: 'signbuddy-d3d91.appspot.com',
    iosClientId: '820561191348-oo83ad65v4gorfpgbicsh3f3aau62qgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.signBuddy.RunnerTests',
  );
}
